### ISSUE TITLE
qmd embed deadlocks at 0% CPU on Apple M5 Max + macOS 26.4 — Metal shader JIT compile failure in bundled llama.cpp b8390 (distinct from #673/#724)

### ISSUE THREAD

**Issue by e3322-pcsk9** [tobi/qmd#735]
## Summary

On **Apple M5 Max + macOS 26.4 Tahoe**, `qmd embed` (and any path that initializes the Metal backend for batch embedding) **deadlocks at 0% CPU** inside `libggml-metal` after `ggml_metal_library_init_from_source: error compiling source`. This is **not** the same root cause as #673 / #724 (those cover the `maxDuration` timeout on *slow-but-progressing* runs). Here the process never makes any progress at all — it hangs in `kevent` waiting on a native async call that never resolves. Patching `maxDuration` does **not** help (verified).

## Environment

| Component | Version |
|---|---|
| qmd | 2.5.3 (`@tobilu/qmd` via bun global) |
| macOS | 26.4 (Build 25E246) |
| Chip | **Apple M5 Max** (Mac17,6; 107.5 GB unified memory) |
| node-llama-cpp | 3.18.1 (bundled) |
| llama.cpp | b8390 (`_nlcBuildMetadata.json`: platform macOS 25.3.0 / arm64 / metal) |
| Embed model | `Qwen3-Embedding-8B-f16.gguf` (14 GB) — also reproduces with the smaller default after `models.embed` is removed |
| Xcode CLT | clang 21.0.0, SDK 26.5 |
| `GGML_METAL_NO_RESIDENCY` | `1` (set by `bin/qmd` launcher per #22593 mitigation) |

## Reproduction

```bash
qmd embed -f              # or: qmd embed --max-docs-per-batch 1 --max-batch-mb 1
```

### Observed output (stays here forever)

```
Model: /Users/.../Qwen3-Embedding-8B-f16.gguf
Batch: N docs / X MB
[node-llama-cpp] ggml_metal_library_init_from_source: error compiling source
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  ← progress bar frozen at 0%
```

### Process state after 5 minutes

```
$ ps -p <PID> -o pid,stat,etime,pcpu,pmem
  PID STAT ELAPSED  %CPU %MEM
 NNNN SN    05:01    0.0 13.2     ← 13.2% MEM = 17.7 GB model loaded, but 0% CPU
```

### `sample <PID> 3` call graph (main thread)

```
1760 Thread_…  DispatchQueue_1: com.apple.main-thread (serial)
+ 1760 start                                   (dyld)
+   1760 node::Start                           (node)
+     1760 node::SpinEventLoopInternal         (node)
+       1760 uv_run                            (node)
+         1760 uv__io_poll                     (node)
+           1760 kevent                        (libsystem_kernel.dylib)   ← blocked here
```

Side thread shows a pending async resolution in the native `llama-addon.node` (`<unknown binary>`) that never completes — consistent with a Metal device init that never returns.

### What does *not* fix it

| Workaround tried | Result |
|---|---|
| Patch `maxDuration` 30 min → 24 h (`store.js:1377`) | Still hangs at 0% CPU from minute 1. **#673's fix does not apply here.** |
| `QMD_FORCE_CPU=1 qmd embed …` | qmd emits `CPU-only llama.cpp prebuilt not available (NoBinaryFoundError); using packaged backend with GPU offloading disabled`, but the Metal-packaged binary still runs `ggml_metal_library_init_from_source` and still hangs. There is no CPU-only prebuilt shipped for `mac-arm64-metal`. |
| `QMD_METAL_KEEP_RESIDENCY=1 qmd embed …` | Same hang. |
| `QMD_LLAMA_GPU=false qmd embed …` | Same as `QMD_FORCE_CPU=1` — packaged Metal binary is still loaded. |

### What does work (for comparison)

- `qmd vsearch "short query"` → 2.2 s end-to-end. Embedding a single short query via Metal succeeds. The hang only triggers when **batch-embedding long chunks**, suggesting the failing shaders are the matmul/attention kernels used for actual forward passes, while device-probe kernels compile fine.
- `qmd doctor` → prints `✓ device probe: GPU metal (macOS Metal backend); offloading enabled; devices: Apple M5 Max; VRAM 107.5 GB free`. The probe is misleading — it passes despite the embedding path being broken, because it doesn't actually run a forward pass with the failing kernels.

## Root cause hypothesis

`llama.cpp b8390`'s embedded `ggml-metal.metal` source code (compiled at runtime via `newLibraryWithSource:options:error:`) **predates the M5 Max GPU architecture** (chip released 2025-09; b8390 is older). On macOS 26.4 the Metal compiler rejects the source outright. There is **no pre-compiled `.metallib` shipped** in `@node-llama-cpp/mac-arm64-metal/bins/mac-arm64-metal/` — runtime JIT compilation is the only path, and it fails.

The failure cascades into a deadlock because `ggml_metal_library_init_from_source` logs the error but the surrounding init code appears to wait on a Metal command queue / device init that never becomes ready, rather than falling back to CPU or aborting cleanly.

## Why this is distinct from #673 / #724

| | #673 / #724 | This issue |
|---|---|---|
| Symptom | Embedding slow, `maxDuration` (10 / 30 min) aborts mid-run | Process **hangs at 0% CPU from minute 1**, no chunks complete |
| Hardware | Various (M5 Pro, Apple Silicon CPU) | **M5 Max specifically** |
| Metal shader | Warning only, "classic Metal kernels work fine" | **Fatal** — init deadlock |
| Patching `maxDuration` | Fixes it | Does **not** help |
| Patching `QMD_FORCE_CPU=1` | (not mentioned; presumably works) | Does **not** help — packaged Metal binary still inits Metal |
| Convergence | Possible via resume runs | **Impossible** — zero progress per run |

## Suggested fixes (any of these)

1. **Ship a CPU-only prebuilt for `mac-arm64`** so `QMD_FORCE_CPU=1` actually avoids loading `libggml-metal` at all (currently the "CPU" fallback still loads the Metal binary). This is the most reliable workaround for affected M5 Max users today.
2. **Bump the bundled llama.cpp** to a release that supports M5 Max's Metal shaders (b8390 is from early 2025; M5 Max shipped Sept 2025).
3. **Fail fast** when `ggml_metal_library_init_from_source` errors — currently the error is logged but execution continues into a deadlock. A clean fallback to CPU (real CPU, not "Metal binary with `gpuLayers:0`") or an explicit abort with an actionable message would be much better than hanging forever.
4. **Make `qmd doctor`'s device probe actually run a forward pass** so it reports `✗ device probe` instead of `✓` when embedding is broken. The current probe is misleading on M5 Max.

## Workaround for affected users

Until a CPU-only prebuilt or newer llama.cpp is shipped, M5 Max users with large embedding workloads have to switch to a smaller model and/or run `qmd embed` repeatedly and hope each invocation makes incremental progress before the Metal deadlock kicks in. In my testing even this is unreliable — some runs make progress (the original 30-min run embedded ~88 chunks before timeout), others deadlock from the first chunk.

## Related

- #673 — `maxDuration` 30 min aborts large corpora (this issue's environment also hits that bug, but it is *not* the primary cause here)
- #724 — same `maxDuration` issue, different angle
- ggml-org/llama.cpp#22593 — the residency-set teardown crash that motivated `GGML_METAL_NO_RESIDENCY=1` in qmd 2.5.3

**Comment by AxelHu** [comment]
Reproduced the same on Apple M4 (Mac mini, M4 10-core, 24GB RAM) + macOS 26.5.1 (Build 25F80). Same symptoms: `qmd embed -f` hangs at 0% CPU in `kevent` after `Model: Qwen3-Embedding-0.6B-Q8_0.gguf` and `Batch: N docs / X MB`. `qmd vsearch` on a single short query succeeds (sub-second end-to-end), so the single-query Metal path is fine.

Key deltas vs. your M5 Max report:
- Chip: Apple M4 (10 GPU cores, 24GB unified). Not M5 Max. So this is **not** M5-Max-specific — it reproduces on M4 too.
- macOS 26.5.1 (Build 25F80) — same minor-line as your 26.4.
- node-llama-cpp 3.18.1 (bundled), llama.cpp b8390, same as yours.
- Embed model: Qwen3-Embedding-0.6B-Q8_0.gguf (~625MB), not the 8B variant. Smaller model still hits the hang.
- `ps` shows 0% CPU / 0.2% MEM (model fits, isn't loaded into process), 8 threads alive, sample shows main thread blocked in `kevent` under `node::SpinEventLoopInternal → uv__io_poll`. GPU was 100% busy at 1475–1578 MHz with ~17W power draw for the full duration — Metal device appears active, but no chunks complete.
- WAL grows (5–9MB) but `vectors_vec_chunks` row count goes from 0→1→2 over 6+ minutes. So writes happen at a rate of roughly **1 vec / 6 min**, which extrapolates to ~10 days to embed 2357 chunks. Unusable.

Things I tried that did not help:
- `--max-docs-per-batch 1 --max-batch-mb 10` (smallest batch).
- `QMD_FORCE_CPU=1` — no CPU-only prebuilt shipped for mac-arm64-metal, packaged binary still loads.
- Killing any concurrent `qmd mcp` server (KeepAlive=false) to remove SQLite + Metal contention.
- Re-launching `qmd embed -f` from a clean state, no mcp server running.

What works:
- `qmd vsearch "RTX 3080" -c <col> -n 1` (single-query embed path) succeeds in well under a second. This is the same `embedBatch([singleQuery])` path that `mcp` uses for live queries — so `memory_search` end-to-end works, it's only the **batch index build** (`qmd embed`) that hangs.
- `qmd update` (incremental re-index of files, no force embed) finishes in ~8s.
- `qmd search` (BM25, no LLM) finishes in well under a second.

My read: your root-cause hypothesis is right — llama.cpp b8390's Metal shader JIT path doesn't compile one or more kernels on Apple Silicon when the embed model is Qwen3-Embedding-0.6B (and probably other Qwen3-Embedding variants). The M4 vs M5 distinction is a red herring; both Apple Silicon chips running macOS 26.x hit the same path.

A "fail fast" path with an actionable error message would be far more useful than the current hang-with-0%-CPU. Even a hard 30-second timeout that surfaces "Metal shader compile failed for this model — try QMD_FORCE_CPU=1 or switch embed model" would be better than waiting 10 days to discover the run made no progress.

I can add a `qmd doctor` patch that runs a single forward pass (not just device probe) to catch this at startup if helpful.

**Comment by LeoLin990405** [comment]
**Confirming on M5 Max — plus a worse failure mode worth flagging**

Same repro here on Apple M5 Max / macOS 26.4, `qmd embed` on the bundled llama.cpp b8390 Metal backend. Your root-cause writeup matches what I see.

One data point to add that's *worse* than the 0%-CPU deadlock: on this machine some `qmd embed` runs don't just hang — the Metal shader-compile path takes the whole box down with a **watchdog hard reset (no kernel panic log written)**. A hang you can `Ctrl-C`; a hard reset you can't, and it can lose unsaved work elsewhere. So the "log-the-error-then-continue-into-a-bad-Metal-init" behavior isn't only a UX problem here, it's occasionally destructive.

What's reliably safe on M5 Max for me is the no-model `qmd search` (BM25) path — it never touches the Metal binary. As you and @AxelHu both found, `QMD_FORCE_CPU=1` is *not* a real escape hatch today, since the packaged `mac-arm64-metal` binary still loads and re-enters the failing init.

On fixes: (1) shipping a CPU-only `mac-arm64` prebuilt and (2) bumping the bundled llama.cpp are both your call — they're packaging/dependency decisions with a blast radius I don't want to guess at. But suggested fix **(3) fail-fast** looks like a clean, self-contained slice that helps regardless of how (1)/(2) land: detect the `ggml_metal_library_init_from_source` error / a no-progress timeout on the embed path and abort with an actionable message ("Metal shader compile failed for this model on this GPU — try a different embed model or BM25 `qmd search`") instead of deadlocking (or, here, occasionally hard-resetting).

I'm set up to repro on M5 Max and happy to open a tightly-scoped PR for (3) — timeout guard + clean abort + message, unit-tested without relying on actually triggering the native hang. Before I do: is (3) the direction you'd want a community PR on, or are you planning to solve this wholesale via a llama.cpp bump? Happy to scope it to whatever's actually useful rather than race the dependency fix.

**Comment by jdcruz-strategy** [comment]
Can corroborate this on a second Apple M5 Max + macOS 26.6 (Build 25G5043d) machine, with one additional data point and two negative-result tests that may help narrow down the fix.

**Environment (matches #735 almost exactly):**
| Component | Version |
|---|---|
| qmd | 2.5.3 (`fd9b97148a`) |
| macOS | 26.6 (Build 25G5043d) — one point release ahead of the original report's 26.4 |
| Chip | Apple M5 Max, 128 GB unified memory |
| node-llama-cpp | 3.18.1 |
| llama.cpp | b8390 (confirmed via `_nlcBuildMetadata.json`) |
| clang | Apple clang 21.0.0 |

**1. The same `ggml_metal_library_init_from_source: error compiling source` fires on `qmd query` (not just `qmd embed`) — but does *not* hang there.**

`qmd query "<text>"`'s "Expanding query..." step hits the identical error message, every time, but the call still completes (~1-1.6s for expansion, normal-speed reranking afterward, correct results). This is consistent with your hypothesis that device-probe/short-embedding kernels compile fine while specific kernels fail — it suggests the failure is per-kernel, and which kernel a given code path needs determines whether you get a silent fallback (query path) or a deadlock (batch `embed` path). Might be worth checking whether the kernel that fails in the query-expansion/single-embed path is the same one failing in batch embedding, or a different one that happens to have a working fallback.

**2. Installing full Xcode + the modular Metal Toolchain does NOT fix it** (ruling out "CLT vs. full Xcode" as the variable):

```
$ xcodebuild -version
Xcode 26.6
Build version 17F113
$ xcodebuild -downloadComponent MetalToolchain   # downloaded + installed, 688MB
$ xcrun -sdk macosx metal --version
Apple metal version 32023.883 (metalfe-32023.883)   # compiler now genuinely present and working standalone
$ qmd query "test"   # still: ggml_metal_library_init_from_source: error compiling source
```

So this isn't a missing-toolchain issue on the host — the standalone `metal` compiler works fine; whatever `ggml-metal.m` is doing at runtime (`newLibraryWithSource:options:error:`) fails independently of that.

**3. Rebuilding from source against `--release latest` is not currently a viable workaround either** (this is new info relevant to suggested fix #2, "bump the bundled llama.cpp"):

```
node dist/cli/cli.js source download --release latest --gpu metal
```

fails to compile on this same Xcode 26.6/clang 21.0.0 toolchain, with **unrelated** errors:
```
AddonContext.cpp:400:41: error: use of undeclared identifier 'cpu_get_num_math'
AddonContext.cpp:748:75: error: use of undeclared identifier 'cpu_get_num_math'
addon.cpp:54:42: error: use of undeclared identifier 'cpu_get_num_math'
addon.cpp:239:29: error: copying variable of type 'std::atomic_bool' ... invokes deleted constructor
```
So bumping the bundled llama.cpp release isn't a drop-in fix today — the addon source itself needs changes (or a different/older intermediate llama.cpp tag) to compile cleanly under the newest Xcode, separately from the Metal shader issue. Whatever release eventually gets pulled in for the M5 Max fix will need to satisfy both constraints.

**4. Likely upstream root cause + existing fix to crib from:** ggml's Metal Performance Primitives changed cooperative-tensor type handling in a way that breaks on macOS 26.2+ — `static_assert failed due to requirement '__tensor_ops_detail::__is_same_v<bfloat, half>'`. Ollama hit the exact same failure mode and fixed it: [ollama/ollama#13460](https://github.com/ollama/ollama/issues/13460), resolved via [ollama/ollama#14604](https://github.com/ollama/ollama/pull/14604). Might be the fastest path to a fix here — whatever ggml commit that PR pulled in (or an equivalent llama.cpp-side fix) is presumably the thing that needs to land in whichever llama.cpp release qmd bundles next.

Happy to test a patched build if one gets cut — have the repro environment set up already.

**Comment by jkudish** [comment]
Hi everyone, thanks for the detailed investigation and follow-ups here. I encountered the same issue on an Apple M5 Max running macOS 26.5.1 with qmd 2.5.3.

I asked my AI coding agent to investigate the failure on my machine and prepare some additional context. It reproduced the macOS behavior, tested alternative execution paths, and verified the following workaround locally.

While native macOS `QMD_FORCE_CPU=1` / `--no-gpu` still initializes the Metal-packaged binary, `@tobilu/qmd@2.5.3` successfully completes batch embedding under Linux/arm64 with `QMD_FORCE_CPU=1`, providing a genuine CPU-only path.

The agent ran qmd in `node:22-bookworm-slim` through OrbStack/Docker, with the corpus and configuration mounted read-only and `/root/.cache/qmd` stored on a Linux-native named volume. The run embedded 2,027 chunks from 213 documents in 9m49s, emitted the expected CPU-only warning, and then passed `PRAGMA wal_checkpoint(TRUNCATE)`, `quick_check`, and `integrity_check`.

This doesn’t fix the macOS backend, but it gives affected users a viable temporary route for building or refreshing indexes. It also seems to add evidence in favor of shipping a genuine CPU-only mac-arm64 prebuilt.

Sharing in case this is useful. I’d be happy to provide the container recipe or have the agent collect any additional diagnostics that would help.
