### ISSUE TITLE
Installing qmd with CUDA on WSL2

### ISSUE THREAD

**Issue by EMRD95** [tobi/qmd#640]
# Installing qmd with CUDA on WSL2 — Complete Guide

> **Quick summary:** WSL2 had old cuBLAS 10.2 stub libraries shadowing the real CUDA toolkit libraries, causing `node-llama-cpp` to link against the wrong version. This guide fixes that and gets qmd running with full GPU acceleration on WSL. The issue might be different for you, my main issue was to compile node-llama-cpp with CUDA properly on WSL2.

---

## Prerequisites

- **WSL2** with a Linux distribution (Ubuntu 22.04+ recommended)
- **NVIDIA GPU** with drivers installed on the Windows host (not inside WSL)
- **CUDA Toolkit** installed inside WSL (see [NVIDIA's WSL guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html))

Verify your setup:

```bash
# GPU must be visible from inside WSL
nvidia-smi

# CUDA toolkit must be installed
nvcc --version

# Node.js >= 22 (or Bun >= 1.0.0)
node --version

# Build tools
cmake --version
```

Example good output:
```
$ nvidia-smi
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.71.01              Driver Version: 596.36         CUDA Version: 13.2     |
|   0  NVIDIA GeForce RTX 3090        On  |    00000000:08:00.0  On |                  N/A |
+-----------------------------------------------------------------------------------------+

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Built on Thu_Mar_19_11:12:51_PM_PDT_2026
Cuda compilation tools, release 13.2, V13.2.75
```

---

## The Problem

WSL2 ships with stub CUDA libraries in the default system paths:

```
/lib/x86_64-linux-gnu/libcublas.so -> libcublas.so.10      # 10.2 from 2019!
/usr/lib/x86_64-linux-gnu/libcublas.so -> libcublas.so.10  # same stubs
```

These stubs (cuBLAS 10.2, circa 2019) predate symbols like `cublasGetStatusString` and are placed in the linker's default search path. When `node-llama-cpp` builds `llama.cpp` with CUDA, CMake's `find_library` picks up these stubs **before** the real CUDA toolkit libraries at `/usr/local/cuda/lib64/`.

The result: `libggml-cuda.so` links against cuBLAS 10.2. At runtime, you get:

```
node: symbol lookup error: libggml-cuda.so: undefined symbol: cublasGetStatusString
```

This happens with **every** CUDA version on WSL — the stubs are always older than the toolkit.

---

### 1. Fix the WSL cuBLAS conflict

Move the old stubs out of the linker's search path:

```bash
# Create a backup directory and move ALL old cuBLAS files there
sudo mkdir -p /lib/x86_64-linux-gnu/old-cublas
sudo mv /lib/x86_64-linux-gnu/libcublas* /lib/x86_64-linux-gnu/old-cublas/ 2>/dev/null
sudo mv /usr/lib/x86_64-linux-gnu/libcublas* /lib/x86_64-linux-gnu/old-cublas/ 2>/dev/null

# Refresh the linker cache
sudo ldconfig
```

Verify only the toolkit's cuBLAS remains:

```bash
ldconfig -p | grep cublas
```

You should see only entries pointing to `/usr/local/cuda/` (or wherever your CUDA toolkit lives), **not** `.so.10`:

```
libcublas.so.13 => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.13
libcublas.so => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so
libcublasLt.so.13 => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.13
libcublasLt.so => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so
```

> **Note:** If you ever uninstall or upgrade your CUDA toolkit, restore the stubs first:
> ```bash
> sudo mv /lib/x86_64-linux-gnu/old-cublas/* /lib/x86_64-linux-gnu/
> sudo ldconfig
> ```

---

### 2. Make sure you're using WSL's npm, not Windows'

This is a common footgun: if you installed Node.js on Windows, its npm may shadow WSL's.

```bash
# Check which npm is in use
which npm
# Should show: /home/<user>/.nvm/versions/node/vXX.XX.X/bin/npm
# NOT: /mnt/c/Program Files/nodejs/npm

# If needed, install Node.js inside WSL via nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
nvm install 22
```

---

### 3. Install qmd

```bash
npm install -g @tobilu/qmd
```

Verify it's the WSL version:

```bash
which qmd
# Should show: /home/<user>/.nvm/versions/node/vXX.XX.X/bin/qmd
# NOT: /mnt/c/Users/.../npm/qmd
```

If you see a Windows path, remove it:

```bash
rm -f /mnt/c/Users/$USER/AppData/Roaming/npm/qmd*
```

---

### 4. Rebuild node-llama-cpp with CUDA

`node-llama-cpp` ships with pre-built CPU binaries. You must rebuild from source for CUDA:

```bash
# Set CUDA environment variables
export CUDACXX=/usr/local/cuda/bin/nvcc
export CUDA_PATH=/usr/local/cuda

# Navigate to node-llama-cpp inside qmd's dependencies
cd "$(npm root -g)/@tobilu/qmd/node_modules/node-llama-cpp"

# Build llama.cpp from source with CUDA backend
node dist/cli/cli.js source download --gpu cuda
```

This step takes **5-15 minutes** depending on your GPU and CPU. It compiles:
- All CUDA kernels (FlashAttention, matrix multiply, quantization)
- The `llama.cpp` library
- The Node.js native addon (`llama-addon.node`)

You'll see progress like:
```
[ 20%] Building CUDA object ... ggml-cuda.dir/rope.cu.o
[ 31%] Building CUDA object ... fattn-mma-f16-instance-...
[ 41%] Building CUDA object ... mmq-instance-q4_k.cu.o
...
[100%] Linking CXX shared library Release/llama-addon.node
✔ Compiled llama.cpp
```

---

### 5. Verify the CUDA build

Check that the compiled library links against the correct cuBLAS:

```bash
ldd "$(npm root -g)/@tobilu/qmd/node_modules/node-llama-cpp/llama/localBuilds/linux-x64-cuda/Release/libggml-cuda.so" | grep cublas
```

Correct output:
```
libcublas.so.13 => /usr/local/cuda/lib64/libcublas.so.13
libcublasLt.so.13 => /usr/local/cuda/lib64/libcublasLt.so.13
```

> **Your version number may differ** (`.so.12`, `.so.13`, etc.) — what matters is that it points to `/usr/local/cuda/`, not `/lib/x86_64-linux-gnu/` or `/usr/lib/x86_64-linux-gnu/`.

---

### 6. Test with a real workload

```bash
# Add a collection
qmd collection add ~/Documents/notes --name notes

# Monitor GPU usage in another terminal
watch -n 1 nvidia-smi

# Generate embeddings (force re-embed with -f)
qmd embed -f
```

If CUDA is working, `nvidia-smi` should show high GPU utilization (70-90%) during embedding.

After embedding, test search:

```bash
# Vector search (fast, no extra models needed)
qmd vsearch "your search terms" -n 5

# Full hybrid search (downloads query expansion + reranker models on first run)
qmd query "your search terms" -n 5 --json
```

---

### `npm install -g @tobilu/qmd` times out

The install tries to compile `node-llama-cpp` with CUDA automatically. Kill it (`Ctrl+C`), then install and rebuild separately:

```bash
npm install -g @tobilu/qmd --ignore-scripts
# Then follow step 4 above
```

### `cublasGetStatusString` still failing after rebuild

The old stubs may still be cached. Double-check:

```bash
# Confirm no cuBLAS in system paths
ls /lib/x86_64-linux-gnu/libcublas* /usr/lib/x86_64-linux-gnu/libcublas*

# If anything besides .bak files exist:
sudo mv /lib/x86_64-linux-gnu/libcublas* /lib/x86_64-linux-gnu/old-cublas/
sudo ldconfig

# Clean and rebuild
rm -rf "$(npm root -g)/@tobilu/qmd/node_modules/node-llama-cpp/llama/localBuilds/linux-x64-cuda"
cd "$(npm root -g)/@tobilu/qmd/node_modules/node-llama-cpp"
CUDACXX=/usr/local/cuda/bin/nvcc CUDA_PATH=/usr/local/cuda node dist/cli/cli.js source download --gpu cuda
```

### `nvcc` not found

Your CUDA toolkit isn't installed or not on PATH:

```bash
# Find nvcc
find /usr/local -name nvcc 2>/dev/null

# If not found, install CUDA toolkit for WSL:
# https://developer.nvidia.com/cuda-downloads
# Choose: Linux → x86_64 → WSL-Ubuntu → 2.0 → deb (local)
```

### `nvidia-smi` works but qmd doesn't use GPU

The Model might be too small to saturate the GPU, or you're running the CPU build:

```bash
# Check which build is active
ls "$(npm root -g)/@tobilu/qmd/node_modules/node-llama-cpp/llama/localBuilds/"
# Should include: linux-x64-cuda/

# If only linux-x64/ exists, repeat step 4
```

### "Cannot find module" or broken install

Start fresh:

```bash
npm uninstall -g @tobilu/qmd
rm -rf ~/.cache/qmd/
# Then follow this guide from step 3
```

---

## Environment Summary

| Component | Version/Path |
|-----------|-------------|
| OS | WSL2 (Ubuntu) |
| GPU | NVIDIA RTX (any) |
| CUDA Driver | Via Windows host |
| CUDA Toolkit | `/usr/local/cuda` |
| cuBLAS (real) | `/usr/local/cuda/lib64/libcublas.so.13` |
| cuBLAS (stubs, removed) | `/lib/x86_64-linux-gnu/old-cublas/` |
| Node.js | `~/.nvm/versions/node/v22.x.x` |
| qmd | `$(npm root -g)/@tobilu/qmd` |
| Models | `~/.cache/qmd/models/` |

---

## References

- [qmd on GitHub](https://github.com/tobi/qmd)
- [node-llama-cpp CUDA guide](https://node-llama-cpp.withcat.ai/guide/CUDA)
- [NVIDIA CUDA on WSL](https://docs.nvidia.com/cuda/wsl-user-guide/index.html)
- [llama.cpp build guide](https://github.com/ggml-org/llama.cpp/blob/master/docs/build.md)

**Comment by while-loop** [comment]
10/10 Guide. I was getting the "no GPU" warnings when using `qmd`. Followed your guide and all is well :)
